### PR TITLE
Add option to run swiftlint only on changed files

### PR DESCRIPTION
**Pull request by axelguilmin**
Hello, I am not really good with bash but I found this solution to check only the files changed in the current pull request. This would help https://github.com/norio-nomura/action-swiftlint/issues/11

### CODE REVIEW

**Review by norio-nomura — COMMENTED** [review]
Thanks for PR!
It looks SwiftLint will lint entire repository when no `*.swift` files are changed in PR.
Is that the behavior you expect?

**Comment by axelguilmin** [comment]
Right, that is not the behavior I expected, I fixed that ;)

**Review by norio-nomura — APPROVED** [review]
Looks good to me. Thanks! 🙏

**Comment by koenpunt** [comment]
While I like the idea of only linting changed files, passing filenames to `swiftlint` makes it ignore the `excluded` configuration, causing it to lint also files that normally would be ignored. 
Another thing I noticed; `github.base_ref` resolves to a branch name, but that branch isn't necessarily available. To get that to work you have to alter the checkout action behavior;

```yml
- uses: actions/checkout@v2
- run: |
    git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
```

Edit; running the additional `git fetch` doesn't solve it.

**Comment by norio-nomura** [comment]
> it ignore the excluded configuration

`--force-exclude` option will resolve it: https://github.com/norio-nomura/action-swiftlint/issues/23#issuecomment-581006372

> Another thing I noticed; `github.base_ref` resolves to a branch name, but that branch isn't necessarily available.

Hm, It seems that happens on `pull_request` against non default branch. 🤔 
Could you please try fetching `base_ref` like following?
```yaml
      - uses: actions/checkout@v1
      - run: |
          git fetch origin +refs/heads/${{ github.base_ref }}:refs/heads/${{ github.base_ref }}
        continue-on-error: true # ignore fail if base_ref points default branch.
```

**Comment by koenpunt** [comment]
> Hm, It seems that happens on `pull_request` against non default branch.

It actually is a PR against `master`, but I'll try your suggestion.

**Pull request merged**
